# build.yml
on:
  pull_request:
    paths:
    - "**"
  push:
    paths:
    - "**"
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - main          # triggers on pushes that contain changes in master

name: Build

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
  
  
  PROJECT_NAME: c2e

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
      
    - name: Deploy
      run: |
        # Deploy
        node -v
        npm install
        npm run build
        aws s3 sync build/ s3://$S3_BUCKET
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*"

